#!/bin/bash

# Borders and spacing
bspc config border_width 2
bspc config window_gap   20

bspc config top_padding    20
bspc config right_padding  30
bspc config bottom_padding 20
bspc config left_padding   30

# Desktops
for mon in $(bspc query -M); do
	bspc monitor $mon -d 1 2 3 4 5 6 7 8 9
done

bspc desktop 1 -l fullscreen
bspc desktop 2 -l tiled

bspc config gapless_monocle    true
bspc config borderless_monocle true

# Rules
bspc rule -a Pidgin floating=on
bspc rule -a mpv floatin=on
bspc rule -a Thunar pseudo_tiled=on
bspc rule -a Transmission-gtk pseudo_tiled=on
bspc rule -a Conky sticky=on manage=off lower=on
bspc rule -a feh floating=on
bspc rule -a meh floating=on


# Something else
bspc config split_ratio           0.50
bspc config focus_follows_pointer true

# Colors
bspc config normal_border_color "#283d48"
bspc config active_border_color "#2c576e"
bspc config focused_border_color "#61859c"
bspc config presel_border_color "#ffffff"
bspc config urgent_border_color "#8772c2"
bspc config focused_locked_border_color "#9a875f"
